apiVersion: v1
kind: Service
metadata:
  name: kanban-ui
spec:
  type: NodePort
  selector:
    app: kanban-ui
  ports:
    - port: 80  # This is the port the container accepts traffic on.
      targetPort: 80  # This is the port inside the container.
      nodePort: 30001  # This is the port on the node.
