apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image: postgres:9.6-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: kanban
        - name: POSTGRES_PASSWORD
          value: kanban
        - name: POSTGRES_USER
          value: kanban
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        emptyDir: {}
